### ISSUE TITLE
PAD of g in M1 calculation

### ISSUE THREAD

**Issue by philippe44** [DCIT/perl-Crypt-SRP#2]
Hi - First, thank you for this module. 
I was trying to use it for a session with an AppleTV. I found that the way ATV expects M1 to be calculated excludes padding of g. So it is
M1 = HASH( HASH(N) XOR HASH(g) | HASH(I) | s | PAD(A) | PAD(B) | K )
and not
M1 = HASH( HASH(N) XOR HASH(PAD(g)) | HASH(I) | s | PAD(A) | PAD(B) | K )
I don't know if this a bug or not, just wanted to let you know

**Comment by karel-m** [comment]
Is there a specification for AppleTV's SRP or at least a couple of test
vectors?

I can add a special flag to `Crypt::SRP->new` like `appletv=>1`. But I need
at least one single test vector.

**Comment by philippe44** [comment]
Unfortunately I don't think there is a spec but I can produce a test vector, knowing that  if you are willing to make that special case, the calculation of K is different as well. It's not H(S) but H(S | 0000) | H(S | 0001) (where 0000 means 4 NULL bytes). 

But I was wondering is the PAD(g) is really an Apple specific thing. I mean, I saw the difference when comparing with a Python (https://github.com/idlesign/srptools/tree/master/srptools) and a Java implementation https://static.javadoc.io/com.nimbusds/srp6a/1.5.3/com/nimbusds/srp6/SRP6Routines.html that do not have a special Apple flag but worked with AppleTV, where the Crypt::SRP did not untill I did the modification.

**Comment by philippe44** [comment]
Hi - To test, you can use

SHA-1, 2048
a = '0xa18b940d3e1302e932a64defccf560a0714b3fa2683bbe3cea808b3abfa58b7d'
I = '0x366B4165DD64AD3A'
P = '1234'
s = '0xd62c98fe76c77ad445828c33063fc36f'
B = '0x4223ddb35967419ddfece40d6b552b797140129c1c262da1b83d413a7f9674aff834171336dabadf9faa95962331e44838d5f66c46649d583ee44827755651215dcd5881056f7fd7d6445b844ccc5793cc3bbd5887029a5abef8b173a3ad8f81326435e9d49818275734ef483b2541f4e2b99b838164ad5fe4a7cae40599fa41bd0e72cb5495bdd5189805da44b7df9b7ed29af326bb526725c2b1f4115f9d91e41638876eeb1db26ef6aed5373f72e3907cc72997ee9132a0dcafda24115730c9db904acbed6d81dc4b02200a5f5281bf321d5a3216a709191ce6ad36d383e79be76e37a2ed7082007c51717e099e7bedd7387c3f82a916d6aca2eb2b6ff3f3'

Should give

M1 = '0x4b4e638bf08526e4229fd079675fedfd329b97ef'
K = '0x9a689113a76b44583e73f9662eb172e830886ed988f04c6c0030f0e93c68784de27dbf30c5d151fb'

**Comment by karel-m** [comment]
It looks like there are more corner cases.

I am thinking about adding:
* `srptools=>1` which turns `Crypt::SRP` into a mode compatible with python package `srptools`
* `appletv=>1`  which turns `Crypt::SRP` into a mode compatible with AppleTV

**Comment by karel-m** [comment]
Could you please try the latest `master`?

It does not work with your test vector but you can perhaps easily check what might be wrong.

**Comment by karel-m** [comment]
Your test vector was wrong:
```diff
- I = '0x366B4165DD64AD3A'
+ I = '366B4165DD64AD3A'
```

Now it seems to work (kind of). See https://github.com/DCIT/perl-Crypt-SRP/blob/master/t/test_appletv.t

**Comment by philippe44** [comment]
Yes, I just saw that, I'm sorry. I is not an hex value but must be kept as a string. I did the test as well and got the expected results

Thank you

**Comment by karel-m** [comment]
released Crypt-SRP-0.018
